export default [
  'coronavirus',
  'covid19',
  'confinement',
  'quarantaine',
  'quarantine',
  'covid-19',
  'ffp2',
  'pandemie',
  'pandemic',
  'covid',
  'coronaviruske',
  'tipsconfinement',
  'stayathome',
  'restezchezvous',
  'covid19fr',
  'flattenthecurve',
  'resterchezsoi',
  'masque',
  'mask',
  'containment',
  'crise sanitaire',
  'covid_19',
  'confiné',
  'confined',
  'prenonssoindesautres',
  'plague',
  'attestation de déplacement',
  'restez chez vous',
  'coronaviré',
  'shutdown',
  'self-isolation',
  'maladie',
  'dépistage',
  'grippe',
  'épidémie',
  'urgence sanitaire',
  'pandémie',
  'virus',
  'crisis',
  '40 aine',
]
